USE [master]
GO
CREATE DATABASE [ECommerce]
	CONTAINMENT = NONE
	ON PRIMARY
( NAME = 'NECommerce', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER2022\MSSQL\DATA\Ecommerce.mdf' , SIZE = 8192KB, MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB)
	LOG ON
( NAME = 'NECommerce_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER2022\MSSQL\DATA\Ecommerce_log.ldf' , SIZE = 8192KB, MAXSIZE = 2048GB, FILEGROWTH = 65536KB)
	WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ECommerce] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECommerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ECommerce] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [ECommerce] SET ANSI_NULLS OFF
GO
ALTER DATABASE [ECommerce] SET ANSI_PADDING OFF
GO
ALTER DATABASE [ECommerce] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [ECommerce] SET ARITHABORT OFF
GO
ALTER DATABASE [ECommerce] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [ECommerce] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [ECommerce] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [ECommerce] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [ECommerce] SET CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE [ECommerce] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [ECommerce] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [ECommerce] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [ECommerce] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [ECommerce] SET ENABLE_BROKER OFF
GO
ALTER DATABASE [ECommerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [ECommerce] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [ECommerce] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [ECommerce] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [ECommerce] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [ECommerce] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [ECommerce] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [ECommerce] SET RECOVERY SIMPLE OFF
GO
ALTER DATABASE [ECommerce] SET MULTI_USER OFF
GO
ALTER DATABASE [ECommerce] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [ECommerce] SET DB_CHAINING OFF
GO
ALTER DATABASE [ECommerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF)
GO
ALTER DATABASE [ECommerce] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [ECommerce] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [ECommerce] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
ALTER DATABASE [ECommerce] SET QUERY_STORE = OFF
GO
USE[ECommerce]
GO
--Tabel  : Table [dbo].[Cart]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cart](
	[ID][int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[UnitPrice] [decimal](18, 2) NULL,
	[Discount] [decimal](18, 2) NULL,
	[Quantity] [int] NULL,
	[TotalPrice][decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF,STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY  = OFF) ON [PIMARY]
)ON [PRIMARY]
GO
--Tabel  : Table [dbo].[Products]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NULL,
	[Manufacturer] [varchar](100) NULL,
	[UnitPrice] [decimal](18,2) NULL,
	[Discount] [decimal](18,2) NULL,
	[Quantity] [int] NULL,
	[ExpDate] [datetime] NULL,
	[ImageUrl] [varchar](1000) NULL,
	[Status] [int] NULL,
PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF,STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY  = OFF) ON [PIMARY]
)ON [PRIMARY]
GO
--Tabel  : Table [dbo].[OrderItems]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OrderID] [int] NULL,
	[ProductID] [int] NULL,
	[UnitPrice] [decimal](18,2) NULL,
	[Discount] [decimal](18,2) NULL,
	[Quantity] [int] NULL,
	[TotalPrice] [decimal](18,2) NULL,
PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF,STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY  = OFF) ON [PIMARY]
)ON [PRIMARY]
GO

--Tabel  : Table [dbo].[Orders]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[OrderNo] [varchar](100) NULL,
	[OrderTotal] [decimal](18,2) NULL,
	[OrderStatus] [varchar](100) NULL,
	[CreatedOn] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF,STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY  = OFF) ON [PIMARY]
)ON [PRIMARY]
GO

--Tabel  : Table [dbo].[Users]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].Users(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](100) NULL,
	[LastName] [varchar](100) NULL,
	[Password] [varchar](100) NULL,
	[Email] [varchar](100) NULL,
	[Fund] [decimal](18,2) NULL,
	[Type] [varchar](100) NULL,
	[Status] [int] NULL,
	[CreatedOn] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF,STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY  = OFF) ON [PIMARY]
)ON [PRIMARY]
GO
--add stored procedures from here
--stored procedure [sp_AddToCart]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[sp_AddToCart](@ID INT, @Email VARCHAR = null, @UnitPrice DECIMAL(18,2) = NULL, @Discount DECIMAL(18,2) = NULL, @Quantity INT = NULL, @TotalPrice DECIMAL(18,2) = NULL)
AS
BEGIN
	DECLARE @UserId INT;
	DECLARE @UnitPrice_ DECIMAL(18,2);
	DECLARE @TotalPrice_ DECIMAL(18,2);
	 



